### ISSUE TITLE
QuickAdd and tp.config.template_file

### ISSUE THREAD

**Issue by sigmoid-azoth** [chhoumann/quickadd#57]
I'm not sure if this is a bug or not, but it seems that files created with QuickAdd overwrite the value of `tp.config.template_file` so that rather than templater seeing `📄 new uri 🔗.md` (template file) as the template TFile, templater sees the new file as the template TFile

I use `tp.config.template_file.path` and `tp.config.template_file.stat.mtime` as a way to keep track of source template versions for generated files

Is there any way around this so that `tp.config.template_file` returns the template TFile as it would with templater?

Example:

#### Source yaml

```yaml
source  :
    template: "[[<% tp.config.template_file.path %>]]"
    version : <% tp.config.template_file.stat.mtime %>
```

#### Insert template via Templater

```yaml
source  :
    template: "[[📁 templates/📄 new uri 🔗.md]]"
    version : 1627216265391
```

#### Create file via QuickAdd (screenshot)

```yaml
source  :
    template: "[[uri~202107250957.md]]"
    version : 1627219317708
```

### QuickAdd Screenshot

![image](https://user-images.githubusercontent.com/87744778/126900446-0c48edfb-8ef8-4895-a4f8-6102cd7cb320.png)
